default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: vladimir
  host: localhost
  pool: 5
  username: vladimir
  password: sqapadcc

test:
  <<: *default

production:
  <<: *default
